#include <iostream>
using namespace std;

int main(){
     int arr[5]={59,24,200,2,0};
     // for (int i=0;i<5;i++)
     // {
     //      for (int j=0;j<5-i-1;j++){
     //           if (arr[j]>arr[j+1]){
     //                int temp=arr[j];
     //                arr[j]=arr[j+1];
     //                arr[j+1]=temp;

                    
     //           }

     //      }
     // }

     // the selection sort algorithum

     
     //now printing the elements of the array
     for(int i=0;i<5;i++){
     cout<<arr[i]<<" ";
     }
}
//now printing the elements of the array
